/**
 * Guarded service-worker registration for Speak30.
 *
 * The SW (/sw.js, generated by vite-plugin-pwa) is registered ONLY in real
 * production builds on the published site. It is never registered in dev,
 * inside iframes, or on Lovable preview hosts — and in those refused
 * contexts any stale Speak30 SW registration is removed instead.
 */

const SW_URL = "/sw.js";

function isRefusedContext(): boolean {
  if (!import.meta.env.PROD) return true;
  if (typeof window === "undefined") return true;
  if (window.self !== window.top) return true; // inside an iframe

  const host = window.location.hostname;
  if (host.startsWith("id-preview--") || host.startsWith("preview--")) return true;
  if (
    host === "lovableproject.com" ||
    host.endsWith(".lovableproject.com") ||
    host === "lovableproject-dev.com" ||
    host.endsWith(".lovableproject-dev.com") ||
    host === "beta.lovable.dev" ||
    host.endsWith(".beta.lovable.dev")
  ) {
    return true;
  }
  if (new URLSearchParams(window.location.search).get("sw") === "off") return true;
  return false;
}

async function unregisterStaleSw(): Promise<void> {
  if (!("serviceWorker" in navigator)) return;
  try {
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(
      registrations
        .filter((reg) => reg.active?.scriptURL.endsWith(SW_URL))
        .map((reg) => reg.unregister()),
    );
  } catch {
    // best-effort cleanup only
  }
}

export async function registerServiceWorker(): Promise<void> {
  if (isRefusedContext()) {
    await unregisterStaleSw();
    return;
  }
  if (!("serviceWorker" in navigator)) return;
  try {
    await navigator.serviceWorker.register(SW_URL, { scope: "/" });
  } catch (error) {
    console.warn("Speak30: service worker registration failed", error);
  }
}
